### ISSUE TITLE
[BUG] Flourish Perk from One Handed does not increase weapon speed by 20%

### ISSUE THREAD

**Issue by yogaraaja** [Geborgen/nordic-souls#10]
**Describe The Bug**
Flourish Perk from One Handed does not increase weapon speed by 20% from Adamant mod.

**Expected Behavior**
One handed weapon speed increased by 20% after taking this perk.

**Send Your Crash Log**
N/A

**Screenshots**
N/A

**List Version**
1.2.3

**Additional Context**
Some users have reported conflict with Pilgrim. Another user have reported that when dual wielding, the main hand weapon speed increased by 20%. But when there is a spell/empty/shield in off hand, weapon speed did not increase by 20%.
You can check current weapon speed by typing "player.getav weaponspeedmult".

**Comment by Geborgen** [comment]
Fixed in v1.3.0
