### ISSUE TITLE
GAME CRASHES ON "NEW SAVE"

### ISSUE THREAD

**Issue by chickemsauce** [Geborgen/nordic-souls#102]
**Describe The Bug**

After running the game through mod organizer it opens correctly, however when pressing "new game" in the start menu the music plays briefly and a black screen shows with a bar in the top right corner before crashing.

**Expected Behavior**

The game to start

**Send Your Crash Log**
If you're reporting a crash, please first verify that **the crash is consistent** and not just random. You can find crash logs in `Documents\My Games\Skyrim Special Edition\SKSE`.

There have been no crash log entries for some reason. This has happened every time i have tried to play.

**Screenshots**

**List Version**
Please state the version of the list you're playing on.

i am on the most recent version as of 11/13/24

**Additional Context**

**Comment by chickemsauce** [comment]
[crash-2024-11-14-00-44-47.log](https://github.com/user-attachments/files/17741409/crash-2024-11-14-00-44-47.log)

**Comment by Geborgen** [comment]
This is not an issue with the list. Please open a support thread in the [Discord](https://discord.com/invite/9cRs3KPyuW) and we'll help you further when we can.
