### ISSUE TITLE
Plaing itrems in safe storage like chest in assigned room 

### ISSUE THREAD

**Issue by IRRIEN** [Geborgen/nordic-souls#105]
**Describe The Bug**
Om a new game I am string items in a safe container in my own  assigned room in the mage college.  After a while when i come back the chest does not display any message to open it and therefore cannot get items that I have placed in there.

**Expected Behavior**
The ability to open the chest and retrieve items

**Send Your Crash Log**
system does not crash

**Screenshots**

**List Version**
Please state the version of the list you're playing on.

**Additional Context**

**Comment by Geborgen** [comment]
Not a bug. Quickloot EE removes the prompt when a container has a large amount of items, to avoid crashing. It should still be accessible.

**Comment by IRRIEN** [comment]
it is not accessible how do I disable quickloot ee?  I have lost items I stored as I cannot open the container.
