### ISSUE TITLE
[BUG] Sprint, Dodge and Shout stop working

### ISSUE THREAD

**Issue by spiritinatomb** [Geborgen/nordic-souls#11]
**Describe The Bug**
At some point during gameplay (have not been able to replicate this as it appears to happen randomly, regardless of being in combat, in doors or inside of cities) the sprint, shout and dodge stop working as well as the interaction (E) key, I can still attack with M1 and use WASD but in first person I cannot see my right-handed weapon and also spells look very small, reloading a save does nothing and the only temporary fix is to reboot the game, which doesn't permanently fix the issue.

**Expected Behavior**
Sprint, Dodge and Shout to work and respond to input.

**Send Your Crash Log**
N/A

**Screenshots**
Will update once I encounter it again.

**List Version**
V1.2.3

**Additional Context**
So far I have noticed:
The bug has only occurred whilst in third-person
The bug tends to happen more during combat, but has happened whilst in in cities like whiterun and just walking around
It can happen as early as 10 minutes into gameplay, or 4 hours

**Comment by Geborgen** [comment]
I have never encountered this nor has anyone else mentioned it. I've kept an eye out for it and will continue to do so, but I'm closing this for now.
