### ISSUE TITLE
[BUG] Invisible building and floating assets.

### ISSUE THREAD

**Issue by Argenthor** [Geborgen/nordic-souls#12]
**Describe The Bug**
The Glathe building south of Skyrim lacks textures. The banners and the Shrine are floating mid air.

**Expected Behavior**
The Shrine of Magnus inside seems to be working properly.

**Screenshots**
![Skyrim - Loredas, 8꞉29 PM, 23rd of Last Seed, 4E 201](https://user-images.githubusercontent.com/123337213/213946912-bbc2056b-564f-4ec8-95cb-702aab1345c1.png)

**List Version**
1.3.2

**Comment by Geborgen** [comment]
Issue with Pilgrim not the list
