### ISSUE TITLE
[BUG] Negative Carry Weight After LotD Supply Sorting

### ISSUE THREAD

**Issue by DepressedOrc** [Geborgen/nordic-souls#13]
**Describe The Bug**
When I use the supply sorting chest in the Legacy of the Dragonborn safehouse, my weight is set to a number in the negative millions and leaves the character permanently over-encumbered. 

**Expected Behavior**
In other versions of LotD's safehouse the Supplies chest has simply taken items away, not reduced the weight to such a negative degree.

**Screenshots**
![image](https://user-images.githubusercontent.com/124714708/217325108-f29e3bda-a8de-47e5-9ccf-05d53b2556c3.png)

**List Version**
Newest

**Comment by Geborgen** [comment]
This is either a bug with LOTD (that I've never experienced) or an issue with console commands, or reloading a save. You could potentially fix it with setav or `modav` console commands. Let me know if you encounter it again, anywhere else, or on 1.4.

**Comment by Geborgen** [comment]
Fixed in version 1.4.2
