### ISSUE TITLE
Invisible arms when using gauntlets on robes

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#15]
What it says in the title
![image](https://user-images.githubusercontent.com/62333062/222853326-9a539415-e7b9-4857-abff-0ec0fe688371.png)
![image](https://user-images.githubusercontent.com/62333062/222853447-fb4af4e7-5fab-4e03-8e89-17cc97608816.png)

**Comment by Geborgen** [comment]
There are a few other instances of this and the truth is... I can't really do anything. It's an issue with the mod and how the outfit is made, and not something I know a whole lot about anyway. Try different sets of robes, or not using gauntlets.
