### ISSUE TITLE
CTD when reading 2 of the recipes in the LotD safehouse

### ISSUE THREAD

**Issue by nicooo** [Geborgen/nordic-souls#16]
- Getting a crash when reading either "Damage Health Poison Recipe" or "Resist Fire Potion Recipe". 

- "Poison Recipe - Paralysis" works fine.

![image](https://user-images.githubusercontent.com/770053/224510794-689db196-82aa-43c8-8f4e-c73abf49b4e7.png)
[Crash_2023_3_11_15-45-36.txt](https://github.com/Geborgen/nordic-souls/files/10949435/Crash_2023_3_11_15-45-36.txt)
[Crash_2023_3_11_15-16-13.txt](https://github.com/Geborgen/nordic-souls/files/10949436/Crash_2023_3_11_15-16-13.txt)
[Crash_2023_3_11_15-21-7.txt](https://github.com/Geborgen/nordic-souls/files/10949437/Crash_2023_3_11_15-21-7.txt)
[Crash_2023_3_11_15-32-54.txt](https://github.com/Geborgen/nordic-souls/files/10949438/Crash_2023_3_11_15-32-54.txt)
[Crash_2023_3_11_15-36-48.txt](https://github.com/Geborgen/nordic-souls/files/10949439/Crash_2023_3_11_15-36-48.txt)

**Comment by Geborgen** [comment]
Hopefully fixed in 1.4.2. If you still have issues feel free to re-open.
