### ISSUE TITLE
Penitus Oculatus armor messed up textures

### ISSUE THREAD

**Issue by devilbyday23** [Geborgen/nordic-souls#17]
Bug Report!

Penitus Oculatus armor textures are borked. 

Affects both male and female bodies and both the player character and NPC's.
![vI67nhS](https://user-images.githubusercontent.com/129234045/228389117-3d0d04f8-228c-4c52-9829-0f8cd0f07479.png)

**Comment by Geborgen** [comment]
Fixed in 2.0
