### ISSUE TITLE
[Purple Around Grass without any added mods]

### ISSUE THREAD

**Issue by Elfie-Mei** [Geborgen/nordic-souls#18]
Grass at any snowy area (for example entrance to Helgen, Winterhold, Dawnstar)  seem to have purple squares around them even with any unadded mods on Nordic Souls This is the latest and current version.

**Comment by Geborgen** [comment]
Could you provide screenshots?

**Comment by Elfie-Mei** [comment]
I'm not sure if Nordic Souls updated recently but when I re downloaded it in order to provide the scren shots you had asked for it seems to have fixed itself. I will keep an eye out in case it is to return.

**Comment by Geborgen** [comment]
I've seen people get purple grass when they try to remove ENB. I'm not sure if you did that, though. Something may have corrupted. Closing for now
