### ISSUE TITLE
[BUG] Halldir's Cairn Consistent Crash

### ISSUE THREAD

**Issue by Izuuk** [Geborgen/nordic-souls#19]
**Describe The Bug**
Halldir's Cairn cave located under Falkreath, entering is fine but after opening the 2nd locked door and walking in it will crash. Seems consistent. No alteration was made from your guide.

**Crash Log**
[Crash_2023_4_14_5-59-25.txt](https://github.com/Geborgen/nordic-souls/files/11229207/Crash_2023_4_14_5-59-25.txt)
[Crash_2023_4_14_6-42-48.txt](https://github.com/Geborgen/nordic-souls/files/11229208/Crash_2023_4_14_6-42-48.txt)

**Screenshots**
![Screenshot 2023-04-14 064926](https://user-images.githubusercontent.com/30009273/231952753-c44bcfaf-c30a-415b-84c1-fffa0519f072.png)

**List Version**
1.4.3

**Comment by Geborgen** [comment]
Archiving this due to legacy version. Submit a new bug report if the issue persists in 2.0
