### ISSUE TITLE
Auri's face is glitched

### ISSUE THREAD

**Issue by yogaraaja** [Geborgen/nordic-souls#2]
**Describe The Bug**
Auri's face is glitched

**Expected Behavior**
Auri's face should look normal

**Send Your Crash Log**
N/A

**List Version**
1.0.1

**Additional Context**
N/A

**Screenshots**
![Screenshot (980)](https://user-images.githubusercontent.com/47807072/199150514-8e2ef881-b3dc-41c5-90d2-7ffe096ddc22.png)

**Comment by Geborgen** [comment]
Thank you for your report. Will be fixed in next update, adding to known issues for now

**Comment by perfektmind** [comment]
Auri replacer needs the main file. The modlist only downloaded the esp replacer.

**Comment by Geborgen** [comment]
Fixed in v1.1.0
