### ISSUE TITLE
[BUG] Death Causes Invisible Right Hand Weapon

### ISSUE THREAD

**Issue by Izuuk** [Geborgen/nordic-souls#20]
**Describe The Bug**
Death causes the right-hand weapon to be invisible until complete restart, no matter the weapon, even swapping seems to affect all, except fists seem to be fine, tried a few things but until I fully restart the game it will stay invisible (meaning the main menu and back does not work)

**List Version**
1.4.3

**Additional Context**
One thought I had was maybe it was because I was loading back as soon as I died pretty quickly, maybe if I left it until the load screen popped up itself but have not tried.

**Comment by Geborgen** [comment]
Archiving this due to legacy version. Submit a new bug report if the issue persists in 2.0
