### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CosmicSloth123** [Geborgen/nordic-souls#21]
Whenever I walk up the road to enter riften my game drops to like 5fps and after 20 seconds or so crashes, and if I load that save or manage to enter riften and try to leave I get stuck on a infinite loading screen, I’m not sure why as It worked fine up until now.

**Send Your Crash Log**
If you're reporting a crash, please first verify that **the crash is consistent** and not just random. A crash log should have been generated in MO2's `Overwrite` folder (at the bottom of the mod list), please upload it.

**Screenshots**

**List Version**
The latest one

**Additional Context**

**Comment by Geborgen** [comment]
Archiving this due to legacy version. Submit a new bug report if the issue persists in 2.0
