### ISSUE TITLE
Sometimes when i shield bash the enemy will stagger and become invincible for a short time

### ISSUE THREAD

**Issue by JadedMynx** [Geborgen/nordic-souls#25]
**Describe The Bug**

**Expected Behavior**

**Send Your Crash Log**
If you're reporting a crash, please first verify that **the crash is consistent** and not just random. A crash log should have been generated in MO2's `Overwrite` folder (at the bottom of the mod list), please upload it.

**Screenshots**

**List Version**
Please state the version of the list you're playing on.

**Additional Context**

**Comment by Geborgen** [comment]
vahlalla combat being valhalla combat im sick of that mod btw
