### ISSUE TITLE
Haugbi and Lawless being overwritten

### ISSUE THREAD

**Issue by IKilledBlitz** [Geborgen/nordic-souls#26]
Hey there, was perusing xEdit and saw that a lot of the changes made by Haugbi and Lawless are reverted back to vanilla by the NPC Appearances merge. If this is intended feel free to close this but I thought I should mention it just in case.

**Comment by Geborgen** [comment]
A lot of it was intended as balancing attempts but these mods are going to be removed so I wouldn't worry about it.
