### ISSUE TITLE
Consistent DragonStalking Bug (dragon corpses following when traveling exterior cells)

### ISSUE THREAD

**Issue by spkyghzt** [Geborgen/nordic-souls#27]
Expected Behavior : Kill dragons without dragon corpses spawning in exteriors cells 

No crash log needed.

List Version : 2.1.1

In the latest update dragon corpses keep following the player. This happens with every dragon you end up killing, forcing you to utilize the disable command and markfordelete command every time this happens ( which is very often) I did play testing on an older version of the list and did not replicate this issue. If you need an unmodified save more then happy to provide. Not game breaking but very annoying. The dragons seems to be the named dragons only (i.e miasma dragon and not "dragon")

**Comment by Geborgen** [comment]
Going to close this due to convo on discord; doesnt seem to happen on new saves and likely unfixable without modifying dragon war's scripts
