### ISSUE TITLE
[USSEP for Onmund/Erik the Slayer/ any follower who uses the same voice not implemented properly.]

### ISSUE THREAD

**Issue by spkyghzt** [Geborgen/nordic-souls#29]
There's a vanilla bug that with dragonborn installed, the follower voice intro when asking to follow says " I suppose master neloth won't mind he's always telling me to get out of his way" in with USSEP is supposed to fix but sometimes doesn't get fully implemented. It's a common thing I noticed with other list (same happened with Elysium in the past) and you might need to go into xedit and patch the dialogue.

List version : 2.1.1

**Comment by Geborgen** [comment]
Not seeing any solution for a while, closing due to discussion in discord
