### ISSUE TITLE
[BUG]Water stops all of a sudden.

### ISSUE THREAD

**Issue by Ishryn** [Geborgen/nordic-souls#3]
**Describe The Bug**
LOD BUG, water stops all of a sudden, as seen below.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 11 06 - 14 01 25 26](https://user-images.githubusercontent.com/69416073/200169604-8e2b6941-0b27-494c-b526-034da70c386c.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 11 06 - 14 01 32 22](https://user-images.githubusercontent.com/69416073/200169609-a7183319-dd46-4684-875d-c479c580a78e.png)

**List Version**
1.0.1

**Comment by Geborgen** [comment]
Fixing for the new update. Please let me know if there are any other landscape bugs like this.
