### ISSUE TITLE
"Adamant - Trade & Barter Patch" has wrong conditions for "Investor" perk

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#30]
The "Investor" perk in Speech can't be skilled. 

The "Adamant - Trade & Barter Patch" has the wrong perk as prerequisite set.

To get it to work  just forwarded the "AdamantBard.esp" changes into the "Adamant - Trade & Barter Patch.esp"
![image](https://github.com/Geborgen/nordic-souls/assets/139084123/cbb3043c-a2f5-4d43-85d8-0be899a30406)

**Comment by Geborgen** [comment]
Fixed in 2.1.2
