### ISSUE TITLE
Mismatched equip animations

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#31]
BUG:
When using a shield the shield sheath animation goes to the back. Shield is supposed to equip on the back with the used animation.
However the shield stays in the offhand after the animations plays.

REASON:
This is because of a mismatch between the used sheath animation (from I think XP32 Skeleton) and the position of shields set in "Simple Dual Sheath".

SOLUTION:
To fix either set "Flags=FirstPerson|Player|NPC" for [ShieldOnBack] in "Simple Dual Sheath" INI.

OR

Change used animation from XPMSE (I do not know how as the in game MCM offers no styles other than default)

**Comment by Geborgen** [comment]
Shields should only show up on back when favorited and unequipped, this was changed with 2.0. XPMSE style animations are very slow to sync up.
