### ISSUE TITLE
Crossbow integration (Thwack + Kachunk load order problem)

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#32]
Base crossbows cannot be crafted atm without first completing both Ancient Technology and The Night Hunter quests.

According to the Kachunk mod (https://www.nexusmods.com/skyrimspecialedition/mods/71081)
"The base crossbows will be craft able with the appropriate perk."

However Thwack (https://www.nexusmods.com/skyrimspecialedition/mods/42653) currently loads after Kachunk and overrides the requirements and adds an additional prerequisite of also completing both Ancient Technology and The Night Hunter quests.

This could be fixed by just changing the load order. However I do not know if this may have additional effects/bugs.
![image](https://github.com/Geborgen/nordic-souls/assets/139084123/5aa3c861-45ae-443c-934a-cbed6d183725)

**Comment by Geborgen** [comment]
Noted, I'll take a closer look at this in a future update.

**Comment by Geborgen** [comment]
fixed in 2.2
