### ISSUE TITLE
[Feature Request] 32:9 Widescreen Support Patch Addition (Updated for 2.2.0.1)

### ISSUE THREAD

**Issue by SirMotte** [Geborgen/nordic-souls#34]
Thank you for your wonderful modpack, I'm still testing things out, but I already fell in love with your collection.

**Describe The Bug**
Currently, when activating the Nordic UI Widescreen Fix, the file "NORDIC UI - COCKS - 21-9 Patch-94128-v1-0-1687592559.7z
" is used, which leads to cut-off UI elements during gameplay with Nordic-UI activated on 32:9 screens (5120x1440).

The Patch Author Wuerfelhuesten provides an additional dedicated 32:9 patch file.
Unfortunately due to my below novice level of mod understanding, I'm unable to install his fix properly.
Wwhenever I use the 32:9 mod file the interface simply reverts back to "Untarnished UI".

**Expected Behavior**
Include 21:9 as well as 32:9 patchfiles as optional files in your widescreen support section. This way inexperienced users (with far too large screens) may be able to properly apply the desired patch.

**Send Your Crash Log**
None

**Screenshots**

**List Version**
2.1.3

**Additional Context**
Samsung Odyssey G9 Neo

32:9 File
https://www.nexusmods.com/skyrimspecialedition/mods/94128?tab=files

**Comment by Geborgen** [comment]
Can you send a screenshot of what the cut off stuff looks like on 32:9?

I didn't add 32:9 support because I assumed it would just be 21:9 but more space on each side. 

Frankly I have no idea how well the included widescreen patch even works for 21:9 monitors as I have no way to test it.

**Comment by SirMotte** [comment]
Main Menu:
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/3c90d0ab-d9d5-4113-9b77-68ca5735056f)

Inventory:
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/45bd2ab4-1fed-43a9-9d9c-2f9eca3df4d3)

Skills Menu:
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/ce0bef78-2eed-4871-8b70-36c47e44f938)

Those are the apparent ones. In general it seems like scaling doesn't work properly and the UI uses the horizontal values as achor points, not vertically.

Just to make sure we are talking about the same fix.
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/aff64ff8-a68b-49a5-bad2-528f722144cc)

**Comment by Geborgen** [comment]
I'll rebuild the widescreen fix and see if I can do something about 32:9.

The main menu is broken anyway and I'm probably going to add a custom one.

**Comment by SirMotte** [comment]
> I'll rebuild the widescreen fix and see if I can do something about 32:9.
> 
> The main menu is broken anyway and I'm probably going to add a custom one.

Awesome, I'm looking forward to it.

**Comment by Geborgen** [comment]
should be fixed in 2.2

**Comment by SirMotte** [comment]
Awesome, thanks!

**Comment by SirMotte** [comment]
Alright, after some testing, here are the results for 2.2.0.1 so far:

There are some still some issues with Nordic UI and the newly implemented fixes present :

- Misaligned Item preview in inventory (neglectable).
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/d4e85a32-5c1d-44e3-84dd-c9b38c718719)

- Impractical Alignment of certain UI Elements
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/55567e89-0961-487b-9d76-35ccb1b425da)
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/555967bc-2ce5-4714-afb3-206f41189ce0)

- Brewing menu out of bounds.
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/e4c8f12c-d55d-472a-a6bf-97d9c34bb9b2)

- Icons are not showing up in the Quick Loot Widget (possibly unsupported by Nordic UI?)
![grafik](https://github.com/Geborgen/nordic-souls/assets/82598692/7e2e56b3-705d-457c-acdb-ddba178352f1)

- Certain Infotext seems to be out of bounds, like injury information and other stuff, will have to look into this in more detail during my new playthrough, I'll report my findings asap.

**Comment by Geborgen** [comment]
I can fix the quickloot but I'll have to dig deeper into everything else. Won't be able to update for a while though.

**Comment by SirMotte** [comment]
> I can fix the quickloot but I'll have to dig deeper into everything else. Won't be able to update for a while though.

No worries, I'll use untarnished for now, take all the time you need.

**Comment by Geborgen** [comment]
Try it again in 2.3.0
