### ISSUE TITLE
[BUG] Vigilant Quest: Bloodsucker Invisible Vampire 

### ISSUE THREAD

**Issue by ChefCook03** [Geborgen/nordic-souls#36]
I’m am doing the first mission in Act 1 of Vigilant called Bloodsucker where I am to find a vampire (Lusine)  in whiterun. I find the vampire and speak with her at night and go through the dialogue, however, when she does her transformation animation (looks like she may have two different looks to her?) she ends up turning completely invisible until I kill her and then she turns into a ash pile. Not sure how to go about fixing this as I believe there may be a quest down the line with a lot more of these vampire which may have the same issue.

She shouldn’t be turning invisible after watching a few YouTube videos of the quest and no one had the issue.

Playing on the list 2.1.3

**Comment by Geborgen** [comment]
Fixed in v2.3.0
