### ISSUE TITLE
[BUG] Food Poisoning from Starfrost gives no negative effects

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#38]
**Describe The Bug**
Eating raw food gives Food Poisoning. However currently the negative effect is not working

The food poisoning mag effect from "Starfrost.esp" is currently being overwritten by "Ring of Namira - Improved for Survival Mode.esp".
Potential fix is probably just changing the load order.

![starfrost food poison](https://github.com/Geborgen/nordic-souls/assets/139084123/5ec54e2f-99b5-4e47-ab52-13946ef68b98)

**Comment by Geborgen** [comment]
Fixed in v2.3.0
