### ISSUE TITLE
[BUG]  Moonstone Heavy Helmet missing meshes

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#39]
Not quite sure on this one. Will mostly just copy&paste the support thread from the discord here:

![20230818224228_1](https://github.com/Geborgen/nordic-souls/assets/139084123/89fb1696-b70b-4c36-99f5-03accae06a8a)

The helmet in question is from here https://www.nexusmods.com/skyrimspecialedition/mods/71372 and is distributed to Khajiit caravans.
When you wear this helmet on a non beast race male it shows this error. This error is afaik missing meshes. Skyrim can't find them so displays a big error instead.

I'm not actually sure this can be considered a bug tbh. As the "moonstone armor" is only there to get distributed to Khajiit. For them this helmet works.
The armor for the player is the Lunar Guard Armor. This one can only be found at one specific place and works.
-> I have not tested if you can just kill the caravan and loot the armor from them. If yes it's easy to get the bugged helmet.

I really do not know what exactly the bug is tbh. Just checked the bsa of tamrielic distribution and it does include meshes and textures for the helmet. So in theory it should work ?

**Comment by Geborgen** [comment]
Closing this as I have not found a solution, and the Tamrielic Distribution author seems unwilling to fix this.
