### ISSUE TITLE
[BUG] CTD when making inputs while opening werewolf perk menu

### ISSUE THREAD

**Issue by Gyzarus-Selene** [Geborgen/nordic-souls#40]
**Describe The Bug**
Whenever pressing A or D while opening the Werewolf perk menu with tab, the game crashes to desktop. 

**Expected Behavior**
Nothing but the perk menu opening, as Tab > A or D is muscle memory from playing in non-beast form. 

**Send Your Crash Log**
[crash-2023-09-10-17-25-45.log](https://github.com/Geborgen/nordic-souls/files/12569692/crash-2023-09-10-17-25-45.log)

**Screenshots**
None available

**List Version**
2.2.0.1

**Additional Context**
Not urgent, as this crash is mainly a skill issue.

**Comment by Geborgen** [comment]
Fixed in v2.3.2
