### ISSUE TITLE
[BUG] Links to Kaidan mods are out of date

### ISSUE THREAD

**Issue by Multox** [Geborgen/nordic-souls#41]
Wabbajack cannot download the following files.  It seems that the links have been changed on kaidanmods.com.

00:00:17.656 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download BWB-HSF-Kaidan-2-Extended-Edition-V8.3.2.7z (HTTPDownloader+State|https://kaidanmod.com/wp-content/uploads/2022/12/BWB-HSF-Kaidan-2-Extended-Edition-V8.3.2.7z)
00:00:17.656 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Kaidan-3DNPC-Patch.7z (HTTPDownloader+State|https://kaidanmod.com/wp-content/uploads/2022/10/Kaidan-3DNPC-Patch.7z)
00:00:17.656 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Kaidan-2-and-Inigo-Banter-Patch-v6.3.7z (HTTPDownloader+State|https://kaidanmod.com/wp-content/uploads/2022/10/Kaidan-2-and-Inigo-Banter-Patch-v6.3.7z)
00:00:17.656 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download BWB-Kaidan-2-Armor-Revamped-Dragon-75089-1-0-1663028606.7z (HTTPDownloader+State|https://kaidanmod.com/wp-content/uploads/2022/10/BWB-Kaidan-2-Armor-Revamped-Dragon-75089-1-0-1663028606.7z)

**Comment by Geborgen** [comment]
Thanks for putting this on github. There is a temporary solution on discord, which works for now while I find time to push an update.

**Comment by Geborgen** [comment]
fixed in 2.2.0.2

**Comment by jmigual** [comment]
Hi This issue seems to be happening again. The links for the mods are dead again.
