### ISSUE TITLE
[BUG] Quests are in Skyrim not working for "Ancient Technology" Quest (Dawnguard)

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#42]
**Describe The Bug**
Quests Are In Skyrim (https://www.nexusmods.com/skyrimspecialedition/mods/18416) should make radiant quests only appear in the vanilla Skyrim Holds. This does not work for "Ancient Technology" (Dawnguard quest) because "CrossbowIntegration.esp" (from Thwack - Crossbow Collection Reworked) loads after it and overrides the change.

Probably just change the load order and all should be good.
![Screenshot2](https://github.com/Geborgen/nordic-souls/assets/139084123/d6aa8105-d76a-4d67-a73e-15612f27647d)

![Screenshot](https://github.com/Geborgen/nordic-souls/assets/139084123/502b4d3a-8eab-4b51-a996-d15f456a4c02)

**Comment by Geborgen** [comment]
Fixed in v2.3.0
