### ISSUE TITLE
[BUG] Hendraheim LOD issue

### ISSUE THREAD

**Issue by annakins** [Geborgen/nordic-souls#44]
**Describe The Bug**
Hendraheim (and possibly others? Great Hall in Skaal Village, according to another user) looks like the pic below for some folks.

**Expected Behavior**
N/A

**Send Your Crash Log**
N/A

**Screenshots**
![image](https://github.com/Geborgen/nordic-souls/assets/92814468/035b43a8-d05a-43a0-9eda-e4b5d58592c6)

**List Version**
2.2.0

**Additional Context**
I have a few additions, but it's just Katana + some armor mods and Honed Metal. I doubt it's relevant in this specific case, but I know that even some mods may not seem like they're conflicting.

**Comment by Geborgen** [comment]
Azura statue seems to be missing for users as well. Will be fixed

**Comment by Geborgen** [comment]
Fixed in 2.3.0; if issue arises again in late-game then reopen issue
