### ISSUE TITLE
[BUG] Wrong download link

### ISSUE THREAD

**Issue by lekugler** [Geborgen/nordic-souls#45]
The Download link for vanguard seems not to be correct. 
I assume they renamed their website from skyrim-guild.com to modding-guild.com

00:00:26.668 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Vanguard+2_2.rar (HTTPDownloader+State|https://www.skyrim-guild.com/s/Vanguard-2_2.rar)

[site here](https://modding-guild.com/mod/vanguard/)

**Comment by Drewbies** [comment]
I also have this problem, don't have a way around it.

**Comment by Geborgen** [comment]
Solution is in the discord. Download manually from modding-guild site until list updates

**Comment by Geborgen** [comment]
Fixed in v2.3.0 (vanguard is no longer used)
