### ISSUE TITLE
Save file fills up with suspended dragonactorscript.OnLoad active scripts

### ISSUE THREAD

**Issue by ForgottenCoast** [Geborgen/nordic-souls#46]
**Describe The Bug**
In mid-late game, skyUI actions such as outfit swtiching become slow. Analysing a saved file with ReSaver shows many (30,000) instances of suspended dragonactorscript.OnLoad scripts

**Expected Behavior**
Ordinarily I believe these scripts are activated when a dragon is killed and then terminate once the dragon soul is absorbed. 

**List Version**
2.4.4

**Additional Context**
I beleive this is a known issue with Dragon Invasion mod - I believe the  Dragonactorscript Infinite Loop Bugfix mod included in Nordic Souls should prevent this happening ordinarily, not sure why its not working here.

** Temporary solution**
Edit save and delete all suspended dragonactorscript.OnLoad scripts

Can also identify the dragon actor  causing the problem with Resave and in console Prid xxxxx followed by disable then markfordelete.

**Comment by Geborgen** [comment]
I'll need to investigate this, not sure why it's happening. The dragonactorscript used to be broken but was fixed in a recent update, not sure what broke it again.

**Comment by ForgottenCoast** [comment]
Can supply a save if you need one, but I guess it probably only tells us what we know already.

**Comment by Geborgen** [comment]
This has not been reproduced since, in versions with updated mods relating to this script. Closing
