### ISSUE TITLE
[BUG] CC Backpacks are invisible when equipped

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#48]
**Describe The Bug**
The backpacks from the creation club content are hidden/invisible when equipped.

**Additional Context**

NS uses this mod https://www.nexusmods.com/skyrimspecialedition/mods/100113 which makes the backpack position customizable via IED. However the preset is currently not merged. This leads to invisible backpacks. If the steps outlined on the mod page are taken the backpacks show up. Don't know if this is something you can setup or if it has to be done by the users.

"To get started, download the mod and install one, or more, of the available files. After you load the game, open up IED's UI.
Navigate to "View>Variables", select one of presets available from the dropdown menu and click on merge:

Then navigate to "View>Display manager>View>Custom items, choose where you want to apply the preset, select one of presets available from the dropdown menu and click on merge:"

**Comment by Geborgen** [comment]
Fixed in v2.3.1
