### ISSUE TITLE
[BUG] Missing Texture at Helgen

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#49]
**Describe The Bug**
There is a missing texture at the Helgen tower. Confirmed on version 2.3.1

![20231223173240_1](https://github.com/Geborgen/nordic-souls/assets/139084123/122c3849-f293-4a42-97f4-06e09294b400)
![20231223173247_1](https://github.com/Geborgen/nordic-souls/assets/139084123/4922449d-fe35-4f2d-a27e-ba9145b42150)

**List Version**
2.3.1

**Comment by Geborgen** [comment]
Fixed in v2.3.2
