### ISSUE TITLE
[BUG]the map is not shown, the screen is purple

### ISSUE THREAD

**Issue by Kodaizero** [Geborgen/nordic-souls#50]
when I press M to open the map, the map is displayed briefly and then the view turns purple, as if a texture is [missing.
![Nordic Souls Map turns Purple](https://github.com/Geborgen/nordic-souls/assets/155012941/c11fda56-7f54-46cf-81bc-e0a27b1e34d8)

**Comment by Geborgen** [comment]
Ensure that NS_PapeMapMerge is the last plugin to load.

**Comment by Kodaizero** [comment]
ok thank you. now it's working.
