### ISSUE TITLE
[BUG] Crashing when Fast Travelling

### ISSUE THREAD

**Issue by refectocil** [Geborgen/nordic-souls#51]
**Describe The Bug**
Caravan to Dawnstar, game crashed. Crashes on fast travel anywhere now. 

**Expected Behavior**
I fast travel and it crashes lol

**List Version**
v2.3.1

**Additional Context**
[crash-2023-12-25-22-32-34.log](https://github.com/Geborgen/nordic-souls/files/13782615/crash-2023-12-25-22-32-34.log)
[crash-2023-12-25-22-35-56.log](https://github.com/Geborgen/nordic-souls/files/13782616/crash-2023-12-25-22-35-56.log)

**Comment by refectocil** [comment]
Update 2: Dawnstar as well.

**Comment by refectocil** [comment]
[crash-2023-12-28-18-03-38.log](https://github.com/Geborgen/nordic-souls/files/13790910/crash-2023-12-28-18-03-38.log)
[crash-2023-12-28-18-34-35.log](https://github.com/Geborgen/nordic-souls/files/13790911/crash-2023-12-28-18-34-35.log)
[crash-2023-12-29-04-18-01.log](https://github.com/Geborgen/nordic-souls/files/13790912/crash-2023-12-29-04-18-01.log)

Crash reports for Riverwood crashes (28th) and Windhelm blacksmith crash (29th)

**Comment by Geborgen** [comment]
Does updating to the latest version of FSMP fix the issue? https://www.nexusmods.com/skyrimspecialedition/mods/57339 let me know in discord if you need assistance, it technically breaks rule 11 so I won't ask you to test it for me. Just wondering if you've tried it.

**Comment by refectocil** [comment]
Can confirm Riverwood and Dawnstar work after updating, will play a bit do some more testing to confirm if it actually fixed it since the crashes didn't seem completely consistent

**Comment by Geborgen** [comment]
Cool, let me know if it works. I am testing on my end as well.

**Comment by refectocil** [comment]
This does break KS Hairdos thought

**Comment by refectocil** [comment]
New crash log, unsure why?

[crash-2023-12-29-22-14-04.log](https://github.com/Geborgen/nordic-souls/files/13796346/crash-2023-12-29-22-14-04.log)

**Comment by Geborgen** [comment]
What happens when you try this version (https://www.nexusmods.com/skyrimspecialedition/mods/57339?tab=files&file_id=381909)

Also how does KS break? I haven't noticed an issue with hdt hair on the new version

**Comment by refectocil** [comment]
Did you want me to try that version for the crashes? Crashes mainly happen upon death now and when trying to load old saves while ingame, can load them from main menu.
![image_2023-12-29_233134137](https://github.com/Geborgen/nordic-souls/assets/12745350/8b789689-d626-42c0-a6f1-600b7f73b8da)

**Comment by Geborgen** [comment]
I wonder if the installation of FSMP is faulty because thats what that means when the hair is like that

**Comment by refectocil** [comment]
Cloaks are also like that to update.

**Comment by refectocil** [comment]
What can I try to fix the cloak/hair issue?

**Comment by Geborgen** [comment]
Make sure that FSMP is installed correctly. It should replace the existing version in the list. Make sure you don't change anything in the fomod when you install.

If you break something you can reinstall the list and it will reset changed files. You can also join the discord server for continued conversation: https://discord.com/invite/9cRs3KPyuW

**Comment by refectocil** [comment]
I'm in the server yeah, do you want me to reach out to u somewhere there? The crashes on death is fixed by the latest version of FSMP you asked me to try at first btw

**Comment by refectocil** [comment]
Ok no need for Discord, I reinstalled FSMP + the KS hairdos patch through the mod launcher and all works now 👍 Thanks for the assist

**Comment by Geborgen** [comment]
Fixed in v2.3.2
