### ISSUE TITLE
[BUG] Stellaris Adept Spells not showing at vendors

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#52]
**Describe The Bug**
via discord, just copy&pasting

The other level 50 resto spells from Darenii's other packs do, but these ones haven't showed up yet.

Update: Asked Dareni directly, added the NPC vendors optional add-on for the mods and put the .esp to load before Natura. Works a treat and adds new merchants that definitely update properly. He said it was an issue with the way the CLI stuff works iirc

**Comment by Geborgen** [comment]
Fixed in v2.3.2
