### ISSUE TITLE
[BUG] "The Defiler" weapon from Artificer unobtainable

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#53]
**Describe The Bug**
The newly added weapon "The Defiler" from Artificer - An Artifact Overhaul is currently unobtainable.

According to the modpage:
"The Defiler is acquired by looting Kodlack’s Key from his bedside table during Glory of the Dead, when Eorlund sends you to retrieve Kodlak’s Journal and his fragment of Wuuthrad."

However the mod "Royal Armory - New Artifacts" prevents this. The key looted from his bedside table "Kodlak's Display Key" opens a different display case with the "Harbinger's Axe". This prevents the looting of the key for "The Defiler". 

**Additional Context**
https://www.nexusmods.com/skyrimspecialedition/mods/99619
https://www.nexusmods.com/skyrimspecialedition/mods/6994

**Comment by Geborgen** [comment]
Update on this issue: I've taken a look at this more than once and this seems to be a bug within artificer itself. I will wait for Artificer to update if this is correct, otherwise I'm going to table this for now.

**Comment by Geborgen** [comment]
Fixed in v2.4.1
