### ISSUE TITLE
Unable to download Data_ccBGSSSE037-Curios

### ISSUE THREAD

**Issue by RIPository69** [Geborgen/nordic-souls#54]
Installations fails with the following log:
 Unable to download Data_ccBGSSSE037-Curios.bsa 
 Unable to download Data_ccBGSSSE037-Curios.esl 

I deleted, verified and redownloaded these files thrice. The issue still persists.

**Comment by Geborgen** [comment]
Verifying files will break it. Please carefully read the "problems with installation" section of the readme.

**Comment by RIPository69** [comment]
Not sure how I managed to overlook that. 😅 Thanks for replying!
