### ISSUE TITLE
[BUG] Found Halberd

### ISSUE THREAD

**Issue by Gyzarus-Selene** [Geborgen/nordic-souls#55]
**Describe The Bug**
Found a halberd in the Dwarvern Storeroom by Mzulft. 

**Expected Behavior**
I remember these weren't supposed to be showing up.

**Screenshots**
![20240107213215_1](https://github.com/Geborgen/nordic-souls/assets/95999173/f173d979-8efd-45b0-aff0-a3c42b668e6d)

**List Version**
2.3.1

**Comment by Geborgen** [comment]
Issue with heavy armory's plugin but I've decided these will be integrated anyway.
