### ISSUE TITLE
[BUG] Stuck on load screen

### ISSUE THREAD

**Issue by gabenorm** [Geborgen/nordic-souls#56]
I load up the game get to the title screen press continue it goes to a load screen with image as backdrop stays on it for around 2 minutes then crashes

i expect it to load normally into the game

Consistant crash logs:
Skyrim SSE v1.5.97
CrashLoggerSSE v1-12-0-0 Dec 15 2023 01:44:43

Unhandled exception "EXCEPTION_ACCESS_VIOLATION" at 0x7FFE6D7326B3 DynDOLOD.DLL+00426B3	mov rcx, [rcx+r12*1]

NORDIC SOULS v2.3.1.1

**Comment by gabenorm** [comment]
I have just realized that other than the load screen issue im also having issues very similar to refectocil so i think it might be the same issue but i think I have the latest version of FSMP as I only downloaded nordic souls two days ago

**Comment by gabenorm** [comment]
[crash-2024-01-09-14-56-28.log](https://github.com/Geborgen/nordic-souls/files/13907366/crash-2024-01-09-14-56-28.log)
[crash-2024-01-09-16-00-19.log](https://github.com/Geborgen/nordic-souls/files/13907367/crash-2024-01-09-16-00-19.log)
[crash-2024-01-09-19-04-19.log](https://github.com/Geborgen/nordic-souls/files/13907368/crash-2024-01-09-19-04-19.log)
[crash-2024-01-10-16-13-26.log](https://github.com/Geborgen/nordic-souls/files/13907369/crash-2024-01-10-16-13-26.log)
[crash-2024-01-10-22-08-44.log](https://github.com/Geborgen/nordic-souls/files/13907370/crash-2024-01-10-22-08-44.log)
[crash-2024-01-10-22-38-04.log](https://github.com/Geborgen/nordic-souls/files/13907371/crash-2024-01-10-22-38-04.log)
[crash-2024-01-11-17-26-54.log](https://github.com/Geborgen/nordic-souls/files/13907372/crash-2024-01-11-17-26-54.log)
[crash-2024-01-11-18-53-38.log](https://github.com/Geborgen/nordic-souls/files/13907373/crash-2024-01-11-18-53-38.log)
the crash logs in full

**Comment by Geborgen** [comment]
Thanks for the crash logs, continuing to diagnose.

**Comment by gabenorm** [comment]
I am also getting an issue when i try to run from MO2 sometimes which is:
Cannot start skse64_loader.exe
With the error code:
Error 5 ERROR_ACCESS_DENIED: Accessisdenied. (0x5)
 . binary: 'C:\Modding Games\Nordic souls\Game Root\skse64_loader.exe'
 . owner: (this user)
 . rights: (normal rights)
 . arguments: ''
 . cwd: 'C:\Modding Games\Nordic souls\Game Root'
 . stdout: no, stderr: no, hooked: yes
 . MO elevated: no
 . usvfs x86:ok x64:ok proxy_x86:ok proxy_x64:ok

I have made the whole nordic souls folder a antivirus exclusion as i thought that might be the issue but it didnt seem to help

**Comment by gabenorm** [comment]
although i think that issue is i need steam running in the background before i open MO2

**Comment by Geborgen** [comment]
Fixed in v2.3.2
