### ISSUE TITLE
[BUG] Ragged Flagon water flickering

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#57]
**Describe The Bug**
Copy&Paste from Discord.
Can confirm this is an issue.

https://streamable.com/ait4xi

"I have not changed the modlist in any way. The water flickers in the ragged flagon. I tried restarting as suggested by another post in the support section but that didn't work. I have had this issue before on a different character and the only thing that fixed it was reloading to a prior save, although that didn't stop it from happening repeatedly. Each time I had to find a save (sometimes several saves back) and reload to resolve this issue. On this character, this is my very first time entering the ragged flagon.

This happened on my other character a month ago, and since then I have uninstalled and reinstalled nordic souls."

**Comment by Geborgen** [comment]
Fixed in v2.3.3
