### ISSUE TITLE
[BUG] Rielle Doors and Casks missing activate prompt

### ISSUE THREAD

**Issue by manneyd15** [Geborgen/nordic-souls#59]
**Describe The Bug**
Multiple small cask containers, the first locked gate leading to the dead orc, and cell door to Rielle Crypt are broken and missing activate Prompt

**Expected Behavior**
Can't activate certain containers, and door to next area. Breaks quest progress.

**Send Your Crash Log**
N/A

**Screenshots**

**List Version**
v. 2.3.2

**Additional Context**
I fixed this bug by installing this mod: https://www.nexusmods.com/skyrimspecialedition/mods/58373?tab=description
(Just dropped it into the mod manager and it automatically sorted to the script fixes section. This is the only change I've made to your list aside from re downloading the Faster HDT-SMP mod and ks hairdos patch because of crashing on fast travel in whiterun/riverwood area, this was a bug report marked as solved in the past and that solution worked. List was otherwise completely untouched until I downloaded the aforementioned Rielle door patch)

From mod author:

"So i was playing the new creation on my heavily modded skyrim (it seems to be all working on the old exe) but i found out that the doors in Rielle couldn't be activated at all. I started investigating and found out through xedit that in the "update.esm" the doors that weren't working had their names as "<Error: Unknown lstring ID 000000F1>, <Error: Unknown lstring ID 000000EF>, <Error: Unknown lstring ID 000000EB>, <Error: Unknown lstring ID 000000F2>" so i opened the english string file for update.esm and looked for the names put them into the esl i created and voilà! Now i can finally open those doors."

**Comment by Geborgen** [comment]
Fixed in v2.3.3
