### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by TomyUs** [Geborgen/nordic-souls#62]
Hi i just tried to download your list, and get this issue:
![Screenshot 2024-03-04 215132](https://github.com/Geborgen/nordic-souls/assets/162191331/809a21ad-d3ee-49c8-b562-89a8287b5dfe)

Any ideas how to solve this?

**Comment by Geborgen** [comment]
You will need to download the Kaidan files manually if they fail, according to the readme. Please visit the [Discord](https://discord.com/invite/9cRs3KPyuW) for further support.

![image](https://github.com/Geborgen/nordic-souls/assets/88332109/475bac4c-3e6e-4140-b052-b45a08a3a93c)

**Comment by TomyUs** [comment]
Thanks a lot!
