### ISSUE TITLE
Alchemy Ingredient Chest In Riverwood Shack Home Unaccessable

### ISSUE THREAD

**Issue by kaycreates** [Geborgen/nordic-souls#63]
I bought the shack in Riverwood from the "tiniest shack" mod, and after storing my items in the alchemy ingredient chest, the UI options for the chest disappeared. I went into the console with the chest selected, and it showed that the items were still stored in the chest, but the UI to search the chest disappeared. I stored 57 types of items, which could be causing the issue because all the other storage areas worked with about 10 items. Here are pictures of the UI not showing up and the console showing the items in the chest.
![alchemy crate](https://github.com/Geborgen/nordic-souls/assets/161745019/2d437648-f514-4354-bf5b-d8ad4529865d)
![console](https://github.com/Geborgen/nordic-souls/assets/161745019/1c24ecfb-004e-4f59-b4b8-56099fbd7de3)

It may be an issue with whichever UI mod displays the items in the chest when looking at it; it probably can't handle the large amount of items. The UI mod shows up for the potion crate and all the other storages, but only the poison crate has default chest UI (shown in images). A test could be done by putting more than 57 items in the poison crate to understand whether the UI mod or the shack is causing issues.
![poison crate](https://github.com/Geborgen/nordic-souls/assets/161745019/5c416816-96d1-48a9-9edb-2da0f9928534)
![potion crate](https://github.com/Geborgen/nordic-souls/assets/161745019/75ba4ca9-1ac8-4c00-9ba8-fcd6d551f1ec)

**Comment by TazerReloaded** [comment]
This is a known issue with QuickLoot EE, it does not display the menu for more than 32 items to prevent crashes.
You can still open the container by pressing the action key while looking at it, or disable QuickLoot.
