### ISSUE TITLE
[BUG] Pressing dodge on the controller opens up the character menu as well

### ISSUE THREAD

**Issue by HugeTaffer** [Geborgen/nordic-souls#64]
Pressing dodge (B) on the controller dodges but also opens up the character menu. Installed through Wabbajack and only modification is checking the controller support mod in mod organizer

**Comment by HugeTaffer** [comment]
Actually managed to fix this by setting all the controls to default in the game's settings. I don't think this is mentioned in the instructions at all, maybe it would be good to point it out so others wouldn't get the same issue?

**Comment by Geborgen** [comment]
This will happen when some controlmap file is overwriting the one in the "gamepad settings" mod, which can happen by editing game settings. I will make note of this soon.
