### ISSUE TITLE
[BUG] Hair is clipping through hat/helmet

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#65]
Self explanatory, hair clips through hats and helmets.

![image](https://github.com/Geborgen/nordic-souls/assets/62333062/6645b144-3d30-4a71-93a1-f149e05ebdf5)
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/b792f8c9-e53d-4496-9a38-7c878f35abeb)

Newest version, installed yesterday

**Comment by Geborgen** [comment]
What hair is this? Is it a wig? This should not happen.

**Comment by Geborgen** [comment]
Confirmed to be issue with that specific hair. I recommend choosing a different hair.
