### ISSUE TITLE
[BUG] Named armour has name removed

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#66]
So I got "Gwendolyn's Hide Armour" at the bandit camp East of Whiterun, gave it to Katana and then went to see if I can give it to Gwendolyn. Found her, looked in Katana's inventory and the name has been replaced with [...] and I can't do anything with it (idk if i could have done anything before the name changed)

![20240319142902_1](https://github.com/Geborgen/nordic-souls/assets/62333062/705ab5dc-1d11-4e87-8dae-1b2c662b4396)
![20240319142909_1](https://github.com/Geborgen/nordic-souls/assets/62333062/fbe1b564-cffb-4eb6-a261-2c898a2054dc)
![20240319142913_1](https://github.com/Geborgen/nordic-souls/assets/62333062/80aaa503-5222-4fb5-8d02-85de24924133)

**Comment by Geborgen** [comment]
I'm not sure what would cause this exactly. For now, reload a save and don't give the armor to Katana to avoid it. This is likely a bug with missives.
