### ISSUE TITLE
Chest in college dorm room stopped interacting

### ISSUE THREAD

**Issue by djscram** [Geborgen/nordic-souls#67]
**Describe The Bug**
I point at the chest and it does not activate even though I have used it in the past and it contains some of my stuff.

**Expected Behavior**
Expected to see the interact prompt, then when I hit R, see all the contents.

**Send Your Crash Log**
If you're reporting a crash, please first verify that **the crash is consistent** and not just random. You can find crash logs in `Documents\My Games\Skyrim Special Edition\SKSE`.

**Screenshots**

**List Version**
Please state the version of the list you're playing on.

**Additional Context**

**Comment by Geborgen** [comment]
Quick Loot stops displaying items after a certain amount are in the chest, to avoid crashes. Open the chest and everything will be there.
