### ISSUE TITLE
[BUG] Modded magika potions use health potion model

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#68]
Again self explanatory, normal potions are fine
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/17d5d42e-52c1-4849-a4a8-6d53666d8726)

However the modded ones that fortify or restore (not sure why that's a different type since the normal ones also restore magika) show up as health potions

![image](https://github.com/Geborgen/nordic-souls/assets/62333062/bfb00592-5405-42cc-92c4-10a0b9d42907)
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/29073ee2-2881-47c1-abe7-7adee196f538)

**Comment by Geborgen** [comment]
This is just a default potion model, not specific to health potions. This is not necessarily a bug, but something I will take a look at either way, I will keep this open for now as low priority.
