### ISSUE TITLE
[BUG] part of "The Bird's Eye"'s floor is floating 

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#69]
self explanatory 
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/5c8ee6b5-eae6-40cd-9cca-f9a2ca8b526e)
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/d85c9733-3842-4264-97aa-173167e94754)

**Comment by Geborgen** [comment]
Fixed in v2.4.0
