### ISSUE TITLE
[BUG] Apothecary Instant Restore Optional Plugin behaves weirdly with Crafted potions.

### ISSUE THREAD

**Issue by yogaraaja** [Geborgen/nordic-souls#7]
**Describe The Bug**
Created potions with the apothecary instant restore value does not change according to new healing values
For instance, at alchemy 20 with the first perk, u can create a healing potion that heals for 7 hp per second for 10 seconds. For reference, minor healing potion heals for 5 hp per second for 10 seconds
But when u use the optional mod to instant restore potions, it only affects the default potions. Minor healing potions heal for 25 while created healing potion heals only for 7.

**Expected Behavior**
Instead of 7 points, it should heal for 27 points

**Send Your Crash Log**
N/A

**Screenshot**

Taken Alchemy Perks:
(Herbalist 1, Concentration 1)
![Screenshot (1033)](https://user-images.githubusercontent.com/47807072/203038394-25262557-aea3-41fc-bf8e-ef1764951a99.png)

With Instant Restore Optional Plugin:
![Screenshot (1031)](https://user-images.githubusercontent.com/47807072/203038142-39edc571-213e-41b6-a991-106d217e11b0.png)

Without Instant Restore Plugin:
![Screenshot (1032)](https://user-images.githubusercontent.com/47807072/203038267-b275356b-f3b9-4b87-b725-dfc3fd93860f.png)

**List Version**
1.2.1

**Additional Context**
N/A

**Comment by Geborgen** [comment]
Will have to update my custom mod, expect it for 1.2.2. Adding to known issues for now
