### ISSUE TITLE
[BUG] Lux or Community Shaders causing significant performance drop

### ISSUE THREAD

**Issue by MrWissenschaft** [Geborgen/nordic-souls#72]
Bug Description:

Performance when indoors is worse than outdoors in most indoor areas. When looking in certain directions, usually where there is a fire or special light source in view.

Without Lux, performance is 110-120 FPS
With Lux, performance is 40-60 FPS

Outdoors, the performance is on par with where it should be for the most part, with only some areas (again, where there are fires or special light sources in view) that have this dip in performance.

This is using Community Shaders and not the ENB, and has been tested on both Windows and Linux.

Some examples are the fires in the middle of inns, the blue light at College of Winterhold Arcaneum, and Dragonsreach for indoor areas.

For outdoor areas, there is the College of Winterhold exterior that slows down at times, but a good example of the hexagon shaped gazebo with the fire housed within outside Whiterun.

Expected Behaviour:

I would expect that performance indoors would at least be on par with if not better than outdoors, with no significant FPS hits when traversing indoor areas, especially small ones with not much going on within, like many of the inns of Skyrim.

Crash logs?:

No crashes involved so no log to produce.

Screenshots?:

No screenshots available but if you want me to send screenshots of my low FPS in these areas I can arrange that.

Version Used:

I am using Nordic Souls version 2.3.4.1

Additional Context:

I believe that Lux, Lux Orbis and/or Lux Via is the cause of this, or is at least interacting with something poorly and is indirectly causing it.

UPDATE:

Hello again

I have tested with Community Shaders and with ENB, and I am getting more FPS with ENB than with Community Shaders, by a large margin indoors, with around 40 FPS for CS in Dragonsreach, and around 90 FPS for ENB in Dragonsreach

**Comment by Geborgen** [comment]
Let me know if you still experience issues in v2.4.0. I have not experienced any.

**Comment by breadland** [comment]
I've had the same problem as MrWissenschaft on v2.4.1.1 of Nordic Souls with CS enabled.

Something that is probably relevant would be my GPU, the 6700XT.

It might be possible that the severe FPS drops only occur on AMD GPUs.
