### ISSUE TITLE
[Missing Requirement] Inconsistency in naming of tempered items

### ISSUE THREAD

**Issue by mealert** [Geborgen/nordic-souls#73]
Nordic Souls uses the Adamant - Smithing Addon. This splits the vanilla tempering system from six﻿ tiers into ten.

However the mod Improvement Names Customized isn't in the list. So tempering still follows the vanilla naming convention.
This may lead to confusion because while an item is called legendary it can still be tempered further. Just need to add the mod to clear up confusion imo.

Relevant mods:

https://www.nexusmods.com/skyrimspecialedition/mods/30191 (Adamant)
https://www.nexusmods.com/skyrimspecialedition/mods/59435 (Improvement Names Customized AE)
OR
https://www.nexusmods.com/skyrimspecialedition/mods/27776 (Improvement Names Customized SSE)

**Comment by Geborgen** [comment]
Fixed in v2.4.0
