### ISSUE TITLE
[BUG] no hunger in survival mode but sleep and warmth work.

### ISSUE THREAD

**Issue by Thevoicingace** [Geborgen/nordic-souls#75]
**Describe The Bug**

**Expected Behavior**

**Send Your Crash Log**
If you're reporting a crash, please first verify that **the crash is consistent** and not just random. You can find crash logs in `Documents\My Games\Skyrim Special Edition\SKSE`.

**Screenshots**

**List Version**
Please state the version of the list you're playing on.

**Additional Context**

**Comment by Thevoicingace** [comment]
I’m not sure if there’s a mod menu option to turn it on or if this is indeed a bug any help would be greatly appreciated

**Comment by Geborgen** [comment]
Not a bug. Starfrost had an old version with no hunger.

**Comment by Thevoicingace** [comment]
Ok is it safe to install the updated version ?

**Comment by Geborgen** [comment]
See the [modification guide](https://github.com/Geborgen/nordic-souls/blob/main/MODIFICATIONGUIDE.md) and the modification channel in my [discord](https://discord.com/invite/9cRs3KPyuW).
