### ISSUE TITLE
[DOCUMENTATION] Readme does not contain any recommendations to disable Untarnished UI when enabling Nordic UI

### ISSUE THREAD

**Issue by lp1641** [Geborgen/nordic-souls#76]
As a result we have markers on the global world map look like in Untarnished UI and compass too, but the rest of the interface looks like in Nordic UI, i.e. everything is mixed.
I think it's worth updating the documentation on this list of mods and add there that people should disable Untarnished UI and its patch for Race Menu when they enable Nordic UI in order to make the whole interface look consistent.

**Comment by Geborgen** [comment]
closing as v2.4.0 removed nordic ui
