### ISSUE TITLE
[BUG] Incorrect trajectory calculation for crossbows

### ISSUE THREAD

**Issue by lp1641** [Geborgen/nordic-souls#77]
**Describe The Bug**
Incorrect trajectory calculation for crossbows. It is calculated in the same way as for arrows but bolt have other physics.
This prevents you from shooting, plus the crossbow bolt flies a bit off the aiming point.

**Expected Behavior**
The same as with bows.

**Send Your Crash Log**
No crashes here.

**Screenshots**
Video 1: https://www.youtube.com/watch?v=K3fE6ypSn7g

UPD:
After some time of playing and after some transitions between locations and other things, the situation even worsens and the trajectory prediction looks the wrong way (somewhere behind the player's back) and also disappears point with the aim as first and third person.

Video 2: https://youtu.be/QIywNRs317k

**List Version**
2.3.4.1 should be latest one

**Additional Context**
In addition to the trajectory we also have an aiming point and bolts do not always fly exactly to this point and sometimes deviate to the right or left, it can also be annoying.
If the trajectory is calculated incorrectly, it can even interfere with normal play.
I use only DLSS Frame Generation mod and no other changes in the mod list, not sure if it's because of it.

**Comment by Geborgen** [comment]
I believe this is an issue with SmoothCam; unfortunately this is out of my ability to fix. I'm not sure if this would be related to frame gen or not, but I recommend trying without it, to see if the issue persists.
