### ISSUE TITLE
[DOCUMENTATION] Mod Manager Gamepad Support and not an obvious issue with ControlMap_Custom.txt

### ISSUE THREAD

**Issue by lp1641** [Geborgen/nordic-souls#78]
If the player has changed the control, he will have in the directory with Nordic Souls folder "overwrite/Root" will be created file "ControlMap_Custom.txt" as a result, even if you turn on "Gamepad Support" in Mod Manager, the settings will be mixed and the buttons will simultaneously perform both old actions and new.
For example, the "B" button on the gamepad will simultaneously open the game menu with the map, skills and everything else, and then make the character dodge, so it's not fun.
And if this point is not fixed, I think it would be worth at least add it to the documentation, the solution is that you need to go to "Nordic Souls/overwrite/Root" and delete from there the file "ControlMap_Custom.txt" and then the controller support will work as it should. There is a possibility that this file is created even if you just opened the "Controls" menu in the game and did not change anything there.
Also "Gamepad Support" makes it so that when switching to the keyboard no longer works dodging, if you could somehow combine this so that when the user switches between gamepad and keyboard nothing changes and he does not have to restart the game and turn off "Gamepad Support" I guess it would be good, but maybe it is too difficult to achieve.

UPD:
Although unfortunately the issue that the character does not always start a sprint when pressing "LB" unfortunately remains. The character randomly either starts a sprint or not.

UPD 2: 
The problem with "LB" and sprint which works unpredictably is solved in the "True Directional Movement" mod settings, found this information here:
https://forum.rewasd.com/forum/rewasd/technical-questions-aa/232359-skyrim-sprint-button-not-working
You need to go to "Miscellaneous" then turn off "Override Controller Deadzone", after that sprint will switch normally with "LB".
I tried to edit "controlmap.txt" removing from there unnecessary assignments "LB" but it did not give results, and apparently it is clear why.
Perhaps this solution should be somehow implemented in the mod settings "Gamepad Support" or "True Directional Movement" for this mod list so that other players do not have this problem. Or in the documentation try to warn people about these possible issues.

**Comment by Geborgen** [comment]
Hi,

I will fix the sprint issue in the new update. Otherwise, I will note the controlmap_custom issue in the readme, as I go through and update all documentation later. Thank you for your report

**Comment by Geborgen** [comment]
Fixed in v2.4.0, will update documentation later
