### ISSUE TITLE
[BUG] Immortal Wild Horse

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#81]
While testing to see if my own wild horse had the 1k bounty on me, I found out that they're immortal.
The horse in question is a grey wild horse I found and tamed outside auri's house in Falkreath.

`kill did not work, and attacking it manually got it's health into the minus's

![20240611184403_1](https://github.com/Geborgen/nordic-souls/assets/62333062/27d39f03-009b-4a9a-af55-4f937ae42f82)

**Comment by Geborgen** [comment]
Not a bug; wild horses are essential.
