### ISSUE TITLE
[BUG] Auri randomly went invisible with no audio

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#84]
Was walking around the college of Winterhold when I realised Auri just up and turned invisible.

When trying to select her with the console, it just select anything that's "behind" her.
![20240613151832_1](https://github.com/Geborgen/nordic-souls/assets/62333062/c48754a3-191e-4c9a-80ad-12f0e406654e)
![20240613152313_1](https://github.com/Geborgen/nordic-souls/assets/62333062/7d62ab46-9c77-48cb-baa1-d5cea8027f49)

She also does not show up on "detect life" abilities, and after you exit dialogue her interact prompt flies away into the void.
https://github.com/Geborgen/nordic-souls/assets/62333062/f4553d14-7f18-4df9-9e7a-3515ecffec53

Have no idea what could've triggered this other than using the command followers key to teleport her every now and again.

She also just as randomly is fine again, so it looks like it fixed itself somehow? Still sending this in so it can be a known bug I guess.

**Comment by Geborgen** [comment]
I'm not sure why this happened, but this seems to be one-off, open a support thread if it happens again/more frequently
