### ISSUE TITLE
[BUG] "Gore" follower doesn't have import to NFF framework option.

### ISSUE THREAD

**Issue by lp1641** [Geborgen/nordic-souls#85]
**Describe The Bug**
"Gore" follower doesn't have import to NFF framework option.

**Screenshots**
https://youtu.be/zEuUm5ZvNwI

**List Version**
2.4.0.1

**Additional Context**
Maybe that's okay for this character but I'm not sure so I leave this here.

**Comment by Geborgen** [comment]
Custom followers should not import to NFF.
