### ISSUE TITLE
[BUG] Serana vampire armor texture

### ISSUE THREAD

**Issue by lp1641** [Geborgen/nordic-souls#87]
**Describe The Bug**
If you look down you'll see that there's a skin texture showing through her armor and it's kind of weird. In the last version 2.3 that I played, her mother Valerica had the same bug, but I haven't gotten there yet in 2.4 so I don't know if she has it too.
But in 2.3 with the previous model of Serana Re-Imagined I don't think I saw this bug.

**Screenshots**
![image](https://github.com/Geborgen/nordic-souls/assets/29174729/bbe177a5-48f1-4098-8688-cf66216ee1c9)
![image](https://github.com/Geborgen/nordic-souls/assets/29174729/7335c901-5f95-44a3-884c-1e5e18ebdee3)

**List Version**
2.4.0.1

**Comment by Geborgen** [comment]
Fixed in v2.4.1
