### ISSUE TITLE
[BUG] Ria's face is incorrect

### ISSUE THREAD

**Issue by Mewsey85** [Geborgen/nordic-souls#88]
Ria is bald and has two different oddly placed face paints

![20240616021056_1](https://github.com/Geborgen/nordic-souls/assets/111457302/ec86782b-29d9-4b20-a4b8-3d48d96ea22e)
![20240616021102_1](https://github.com/Geborgen/nordic-souls/assets/111457302/8a85c4a3-be3e-4bbd-9a45-077d4b4591c9)

**Comment by Geborgen** [comment]
Fixed in v2.4.1
