### ISSUE TITLE
Rune Master Perk not working

### ISSUE THREAD

**Issue by borish43b** [Geborgen/nordic-souls#89]
The Rune Master perk from the destruction tree still does not work correctly. When you invest a point with no rune active, you can always only cast a single rune regardless of your investment in the perk. When you have already a rune active when you spend a point, you can cast an infinite amount of runes. This was already true for NS <2.4.

**Expected Behavior**
One Rune can be casted with the perk, two with the first level and three with the second level.

There is already a mod that fixes the issue and it seems to work (Rule 11 however):
https://www.nexusmods.com/skyrimspecialedition/mods/83381?tab=description

**Comment by Geborgen** [comment]
Fixed in v2.4.1
