### ISSUE TITLE
[BUG] Wrong magicka costs for some spells (runes)

### ISSUE THREAD

**Issue by ribeirojc1** [Geborgen/nordic-souls#9]
**Describe The Bug**
I don't know about other spells, 'cause I've only played for a couple of hours.
But rune costs are messed up.
I even started a new game and added some gold, to show the **values without perks and gear**.
Frost and lightning rune costs are too low for no reason.
Any idea on how to fix it?

**Expected Behavior**
Frost and lightning runes magicka costs should be higher (similar to fire rune).

**Send Your Crash Log**
Not CTD related.

**Screenshots**
![Dragonsreach_-_Sundas_1054_AM_17th_of_Last_Seed_4E_201_-_Copy](https://user-images.githubusercontent.com/91457791/208247611-5c63bf66-11ad-4f88-85af-1298d06653ff.png)

**List Version**
Latest (downloaded december 16th). 
ver 1.2.3

**Additional Context**
Tried on two different characters, just to be sure. Same results on both of them.

**Comment by Geborgen** [comment]
Thanks for the report. Will be fixed in 1.3

**Comment by ribeirojc1** [comment]
I'm checking xedit right now.
It seems the problem lies with mysticism itself.
Mysticism's base cost (see attached pictures):

- Fire: 2.250
- Frost: 2.075
- Shock (lightning): 2.425
- Poison: 17.5
- Sun : 2.385

That value is overwritten by enb light and synthesis for fire rune, but not for the rest.
The vanilla (used by synthesis for fire rune) values are:
- Fire: 40
- Frost: 50
- Shock: 55
- Poison: 22
- Sun : none

I don't think Simon intended for such low values. Runes are strong as hell (and a really good way to level destruction). Even with a high cost they're absurdly good. 

![image](https://user-images.githubusercontent.com/91457791/208263136-ddb4b862-927b-4298-9683-947b4bc27a2e.png)
![image](https://user-images.githubusercontent.com/91457791/208263171-a5915f48-4972-4243-90cd-4536d8fdd41e.png)
![image](https://user-images.githubusercontent.com/91457791/208263365-6b5b9d1a-4b11-430f-a53a-9eaef4987664.png)
![image](https://user-images.githubusercontent.com/91457791/208263746-8788f9c3-464d-4dd8-9bd2-c790956ed23b.png)
![image](https://user-images.githubusercontent.com/91457791/208264040-5afc433e-6834-4153-a05b-8f0a41c79c86.png)

**Comment by ribeirojc1** [comment]
The values bellow were obtained after messing with xedit.

![Dragonsreach - Sundas, 10꞉59 AM, 17th of Last Seed, 4E 201](https://user-images.githubusercontent.com/91457791/208265279-05060c57-580f-4a24-9900-f3e02bf8a480.png)

I just edited MysticismMagic.esp (I know the right way to solve this would be creating a patch, but I'm too lazy for that).
Reverted back to vanilla values.
For sun rune I used a base cost of... not sure now... 53 I guess (a little less than shock).

By the way, I redownloaded the mod, to make sure it wasn't some problem with my wabba downloads folder.

**Comment by Geborgen** [comment]
Thank you so much for looking into this, I haven't been able to do much recently as I've been sick but I plan to completely re-work patching anyway. 1.3 will have to be pushed back due to said delays, I'm glad you got something working for you at this moment though

**Comment by Geborgen** [comment]
Fixed in v1.3.0
