### ISSUE TITLE
Floating Grass in Durnehviir Boneyard fight

### ISSUE THREAD

**Issue by Docodo3** [Geborgen/nordic-souls#90]
Grass is floating above the boneyard making it very difficult to fight.

To have the grass placed normally 

![20240616_222123](https://github.com/Geborgen/nordic-souls/assets/173081266/9ee3f5d1-c415-47d7-b433-ccb7a19505e0)

Nordic Souls version 2.4.0.1

**Comment by Geborgen** [comment]
This is a deeper issue that will require more time to diagnose. It seems to sometimes correct itself when reloading the game, or you can use "tg" to toggle grass during the fight for now.
