### ISSUE TITLE
[BUG] "Conjure Ancestral Guardian" seemingly counts as 2 summons

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#92]
While wearing the warlock's mark, summoning anything and then proceeding to summon an ancestral guardian will kill the first summoned creature, however you are then able to summon it again afterwards. This is unless it is another ancestral guardian, in which case it will kill the first one.
![image](https://github.com/Geborgen/nordic-souls/assets/62333062/1b1353fc-5dd9-457f-bc46-0e80ec7e9f36)
Video for clarity
https://github.com/Geborgen/nordic-souls/assets/62333062/fbb0fde8-e7df-4a77-9b15-a846d97ca6cd

**Comment by Geborgen** [comment]
This appears to be default mysticism behavior.
