### ISSUE TITLE
[BUG] Thalmor prisoner alternate start is bugged

### ISSUE THREAD

**Issue by Okibon** [Geborgen/nordic-souls#94]
Loaded into the cell, tried talking to the khajiit, the thalmor guards just decide to shoot him to death for some reason.

![20240622194436_1](https://github.com/Geborgen/nordic-souls/assets/62333062/66071fab-e5d6-4c44-8d28-8adcf64e36ba)

Then when you escape they aren't even hostile to you.

![20240622194548_1](https://github.com/Geborgen/nordic-souls/assets/62333062/a5ee9339-16b3-4e79-9cc8-d7916bd4d406)

**Comment by Geborgen** [comment]
This start is known to be buggy with ASLAL new beginnings, use a different start.
