### ISSUE TITLE
[BUG] PLEASE install "Run For Your Lives" and "Simply Knock" and "Destroy The Thieves Guild" and "My Minimalistic Autosave"

### ISSUE THREAD

**Issue by TheOneLiliad** [Geborgen/nordic-souls#96]
**Describe The Bug**
I'm sick of NPCs dying from dragon and vampire attacks unnecessarily

**Expected Behavior**
NPCs should run into their house

![image_2024-07-07_015609140-min](https://github.com/Geborgen/nordic-souls/assets/153738427/0c8f495d-ab46-416e-aca6-67f8854a73bd)

**List Version**
Version 2.4.1

**Comment by Geborgen** [comment]
Please use this for bug reports.
