### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JessieKr** [Geborgen/nordic-souls#97]
Can't run the game via ModOranizer, got the message "**the application must run to completion because its output is required**" and then nothing happened

I did:
   1. Prerequisites (C++, NET, disable OneDrive, Steam autoupdate, overlay)
   2. Set up Skyrim to English
   3. Set up Pagefile and Shader Cache Size
   4. Donload all CC content on fresh copy
   5. Sucessfully installed all mods via wabbajack
   6. Add folders in Exclusion ![image](https://github.com/Geborgen/nordic-souls/assets/18751544/ced69170-ebfb-4146-8792-dc596e1ca94c)
   7. When I click RUN in ModOrganizer.exe this message Pop-UP 
   ![Screenshot 2024-07-08 130011](https://github.com/Geborgen/nordic-souls/assets/18751544/89c5bb9e-fd21-480a-8de6-f724f1556ecf)
I see that on Steam the game starts (the button changes from “play” to “close”, but Skyrim itself does not start) after 10-15 seconds the message window in ModOrganizer disappears and on Steam the “close” button changes back to “play”. 
  8. Then some loading occurs in ModOrganizer after which nothing happens 
  ![image](https://github.com/Geborgen/nordic-souls/assets/18751544/7d57da0e-806a-412a-8f20-740aac2c85cf)
  9. Checked the logs of mo_interface, which indicate that the RivaTuner (MSI Afterburner) program may cause problems. Exit the program. I tried to run it again and nothing happened, this time the logs seemed to be without errors.
[mo_interface.log](https://github.com/user-attachments/files/16126387/mo_interface.log)
  10. Checked the logs of usvfs-2024 and it seemed to be withouth errors. [usvfs-2024-07-08_10-33-16.log](https://github.com/user-attachments/files/16126448/usvfs-2024-07-08_10-33-16.log)

Steam itself     is installed in the path  _C:\Program Files (x86)\Steam_
Skyrim             is installed in the path  _F:\SteamLibrary\steamapps\common\Skyrim Special Edition_
Wabbjack        is installed in the path  _F:\wabbajack_
Nordick Souls is installed in the path _F:\Nordic Souls_

F: disc got 20 Gb assigned to Pagefile and now I have 100+ Gb of free space left

**Comment by Geborgen** [comment]
Hi, could you open a support thread in discord? It will be easier to help there.
